/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.74
* Sun Feb 16 23:38:47 PST 2014
* 
* Call the script: _dummy = this execvm "american.sqf";
* 
*/


while {true} do {
 if isnull _this exitwith {};
 if not alive _this exitwith {};
 clearweaponcargo _this;
 clearmagazinecargo _this;

 _this addweaponcargo ["M9",5];
 _this addweaponcargo ["M1014",1];
 _this addweaponcargo ["MP5SD",1];
 _this addweaponcargo ["MP5A5",1];
 _this addmagazinecargo ["15Rnd_9x19_M9",50];
 _this addmagazinecargo ["8Rnd_B_Beneli_Pellets",5];
 _this addmagazinecargo ["30Rnd_9x19_MP5",5];
 _this addmagazinecargo ["30Rnd_9x19_MP5SD",5];

 sleep 600;
};
