/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.74
* Sun Feb 16 23:31:49 PST 2014
* 
* Call the script: _dummy = this execvm "simple.sqf";
* 
*/


while {true} do {
 if isnull _this exitwith {};
 if not alive _this exitwith {};
 clearweaponcargo _this;
 clearmagazinecargo _this;

 _this addweaponcargo ["Makarov",10];
 _this addmagazinecargo ["8Rnd_9x18_Makarov",100];

 sleep 600;
};
