/**
* Generated by LEA for Arma 2 Combined Operation & ACE 2
* Version: 1.4.74
* Sun Feb 16 23:32:36 PST 2014
* 
* Call the script: _dummy = this execvm "strong.sqf";
* 
*/


while {true} do {
 if isnull _this exitwith {};
 if not alive _this exitwith {};
 clearweaponcargo _this;
 clearmagazinecargo _this;

 _this addweaponcargo ["LeeEnfield",1];
 _this addweaponcargo ["AKS_GOLD",1];
 _this addweaponcargo ["revolver_EP1",3];
 _this addweaponcargo ["revolver_gold_EP1",2];
 _this addmagazinecargo ["10x_303",6];
 _this addmagazinecargo ["30Rnd_762x39_AK47",6];
 _this addmagazinecargo ["6Rnd_45ACP",50];

 sleep 600;
};
